import {
  HomeEnvironmentRequirementDefinition,
} from './home-environment.models';

export const HOME_ENVIRONMENT_REQUIREMENTS: HomeEnvironmentRequirementDefinition[] = [
  {
    ruleCode: '565.23(b)(1)',
    citation: 'TAC §565.23(b)(1)',
    title: 'Interior and exterior condition',
    description:
      'Residence is maintained in good repair and free from conditions that create health or safety risks.',
    category: 'CONDITION',
    sortOrder: 1,
    defaultSeverity: 'HIGH',
    evidenceTypes: ['NOTE', 'PHOTO', 'CHECKLIST'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(2)',
    citation: 'TAC §565.23(b)(2)',
    title: 'Hazard-free living areas',
    description:
      'Living areas are free from observable hazards such as broken surfaces, sharp edges, exposed risks, or unsafe conditions.',
    category: 'HAZARDS',
    sortOrder: 2,
    defaultSeverity: 'HIGH',
    evidenceTypes: ['NOTE', 'PHOTO', 'CHECKLIST'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(3)',
    citation: 'TAC §565.23(b)(3)',
    title: 'Safe and functional furnishings',
    description:
      'Furniture and fixtures are safe, usable, and appropriate for the individuals served.',
    category: 'FURNISHINGS',
    sortOrder: 3,
    defaultSeverity: 'MEDIUM',
    evidenceTypes: ['NOTE', 'PHOTO'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(4)',
    citation: 'TAC §565.23(b)(4)',
    title: 'Adequate sanitation',
    description:
      'Residence is clean and sanitary, including kitchens, bathrooms, sleeping areas, and common spaces.',
    category: 'SANITATION',
    sortOrder: 4,
    defaultSeverity: 'HIGH',
    evidenceTypes: ['NOTE', 'PHOTO', 'INSPECTION_LOG'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(5)',
    citation: 'TAC §565.23(b)(5)',
    title: 'Safe water and utility condition',
    description:
      'Water, plumbing, and essential utilities are available and maintained in safe working order.',
    category: 'SAFETY',
    sortOrder: 5,
    defaultSeverity: 'HIGH',
    evidenceTypes: ['NOTE', 'CHECKLIST', 'INSPECTION_LOG'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(6)',
    citation: 'TAC §565.23(b)(6)',
    title: 'Lighting and ventilation',
    description:
      'Residence has adequate lighting and ventilation to support health, comfort, and safety.',
    category: 'SAFETY',
    sortOrder: 6,
    defaultSeverity: 'MEDIUM',
    evidenceTypes: ['NOTE', 'PHOTO'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(7)',
    citation: 'TAC §565.23(b)(7)',
    title: 'Temperature and environmental comfort',
    description:
      'Residence supports safe indoor temperature and environmental conditions appropriate to the season and resident needs.',
    category: 'SAFETY',
    sortOrder: 7,
    defaultSeverity: 'HIGH',
    evidenceTypes: ['NOTE', 'CHECKLIST'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(8)',
    citation: 'TAC §565.23(b)(8)',
    title: 'Toilet and bathing facilities',
    description:
      'Bathrooms and bathing facilities are functional, sanitary, and safe to use.',
    category: 'SANITATION',
    sortOrder: 8,
    defaultSeverity: 'HIGH',
    evidenceTypes: ['NOTE', 'PHOTO', 'CHECKLIST'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(9)',
    citation: 'TAC §565.23(b)(9)',
    title: 'Kitchen and food preparation safety',
    description:
      'Kitchen and food preparation areas are clean, safe, and maintained for sanitary use.',
    category: 'SANITATION',
    sortOrder: 9,
    defaultSeverity: 'HIGH',
    evidenceTypes: ['NOTE', 'PHOTO', 'CHECKLIST'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(10)',
    citation: 'TAC §565.23(b)(10)',
    title: 'Bedroom condition and suitability',
    description:
      'Bedrooms are maintained in safe condition and are appropriately furnished and arranged.',
    category: 'FURNISHINGS',
    sortOrder: 10,
    defaultSeverity: 'MEDIUM',
    evidenceTypes: ['NOTE', 'PHOTO'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(11)',
    citation: 'TAC §565.23(b)(11)',
    title: 'Storage and housekeeping',
    description:
      'Residence supports orderly storage of supplies, personal items, and household materials without creating hazards.',
    category: 'CONDITION',
    sortOrder: 11,
    defaultSeverity: 'MEDIUM',
    evidenceTypes: ['NOTE', 'PHOTO'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(12)',
    citation: 'TAC §565.23(b)(12)',
    title: 'Laundry and linen condition',
    description:
      'Laundry and linen practices support cleanliness, sanitation, and safe household operation.',
    category: 'SANITATION',
    sortOrder: 12,
    defaultSeverity: 'MEDIUM',
    evidenceTypes: ['NOTE', 'CHECKLIST'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(13)',
    citation: 'TAC §565.23(b)(13)',
    title: 'Pest and infestation prevention',
    description:
      'Residence is free from pests or infestation and evidence of prevention/control is maintained.',
    category: 'SANITATION',
    sortOrder: 13,
    defaultSeverity: 'HIGH',
    evidenceTypes: ['NOTE', 'PHOTO', 'DOCUMENT'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(14)',
    citation: 'TAC §565.23(b)(14)',
    title: 'Trash and waste handling',
    description:
      'Trash, waste, and potentially unsanitary materials are stored and disposed of safely.',
    category: 'SANITATION',
    sortOrder: 14,
    defaultSeverity: 'MEDIUM',
    evidenceTypes: ['NOTE', 'PHOTO'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(15)',
    citation: 'TAC §565.23(b)(15)',
    title: 'Indoor and outdoor access safety',
    description:
      'Entrances, exits, walkways, and exterior areas are maintained in safe condition.',
    category: 'SAFETY',
    sortOrder: 15,
    defaultSeverity: 'HIGH',
    evidenceTypes: ['NOTE', 'PHOTO', 'CHECKLIST'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(16)',
    citation: 'TAC §565.23(b)(16)',
    title: 'Chemical and hazardous material safety',
    description:
      'Chemicals, cleaning supplies, and hazardous materials are handled and stored safely.',
    category: 'HAZARDS',
    sortOrder: 16,
    defaultSeverity: 'CRITICAL',
    evidenceTypes: ['NOTE', 'PHOTO', 'CHECKLIST'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(17)',
    citation: 'TAC §565.23(b)(17)',
    title: 'Appliance and equipment condition',
    description:
      'Household appliances and equipment are in safe working order and do not create avoidable risk.',
    category: 'SAFETY',
    sortOrder: 17,
    defaultSeverity: 'HIGH',
    evidenceTypes: ['NOTE', 'PHOTO', 'INSPECTION_LOG'],
    active: true,
  },
  {
    ruleCode: '565.23(b)(18)',
    citation: 'TAC §565.23(b)(18)',
    title: 'Overall residential safety and habitability',
    description:
      'Residence supports a safe, sanitary, functional, and habitable environment for individuals served.',
    category: 'SAFETY',
    sortOrder: 18,
    defaultSeverity: 'HIGH',
    evidenceTypes: ['NOTE', 'PHOTO', 'CHECKLIST', 'INSPECTION_LOG'],
    active: true,
  },
];